### ISSUE TITLE
偏愛のありなし機能を作る

### ISSUE THREAD

**Issue by manntera** [manntera/arad-buff-score-measure#11]
完全に忘れてた。
レスポンスの仕様どうしようか。

**Comment by manntera** [comment]
https://discord.com/channels/1042102410857951273/1223122141390835742/1224584131552481341

偏愛の性能は禁断に依存しているのでスクショは必要ありません
スコア計算時に偏愛ありの場合は禁断の知能に1.15✕
禁断にの物理攻撃力に1.15倍にすることで算出します

**Comment by manntera** [comment]
https://discord.com/channels/1042102410857951273/1223122141390835742/1224586339824046185
偏愛はうってもうたなくても表示される禁断のバフ数値はおなじです

**Comment by manntera** [comment]
# 案１
リクエストパラメーターに isHenai(仮)をつける。
→trueがあった場合でかつ、偏愛があった場合、偏愛ありのスコアを返す
→クライアントでスコアを返す時が楽。ありなし両方知りたい場合２回リクエストを送る必要がある

# 案2 
レスポンスパラメーターにHenaiParamを付ける
→スクショの中に禁断が見つかれば偏愛のスコアもレスポンスに含める
→リクエストが１回で済む
→クライアントで偏愛用のifが必要

**Comment by manntera** [comment]
https://discord.com/channels/1042102410857951273/1223122141390835742/1224606909030600755
案２で

**Comment by manntera** [comment]
HenaiScoreか
PartialityScoreか
どっちが好みですか？
@mtakuma1110

**Comment by mtakuma1110** [comment]
Henai派だけど、どうしてもHentaiに見えるのが難点、、、

**Comment by manntera** [comment]
じゃあHenaiでいきますねー。
Hentaiに見えるのはそれはそう…

**Comment by manntera** [comment]
偏愛込みバフスコアの計算が合わない…

**Comment by manntera** [comment]
まず、元の計算式はスプレッドシートの下記を参照しています。
=ROUNDDOWN((((J50*1.15+L50+N50+P50+15000)/250+1))*(K50*1.15+O50+2650)/10,0)
計算のコードは下記です。
https://github.com/manntera/arad-buff-score-measure/blob/add_partialityScore/calculate-score-api/pkg/Repository/BuffScoreRepo/BuffScoreRepo.go

恐らく同じ計算式のはずなんですけどね…
コード分かる人にレビューして欲しい…

@mtakuma1110 ちょっと計算式のレビューお願いします。

**Comment by manntera** [comment]
![image](https://github.com/manntera/arad-buff-score-measure/assets/20245518/bddd7ea4-b4b4-42d2-bc55-df2560958436)

入力値は間違ってないはず…

**Comment by MuhammadJr01** [comment]
禁断以外のスキルの知能や　禁断以外のスキルの物理攻撃力にも　１．１５がかかっていませんか

**Comment by MuhammadJr01** [comment]
参照しているスプシの普段は非表示にしているI行の中身が偏愛ありの場合の計算式です

**Comment by manntera** [comment]
> 参照しているスプシの普段は非表示にしているI行の中身が偏愛ありの場合の計算式です

https://github.com/manntera/arad-buff-score-measure/issues/11#issuecomment-2039705872
これであってますよね？

**Comment by MuhammadJr01** [comment]
float32
の意味するところがわからない
この中に禁断以外のスキルつまり覚醒・パペット・小悪魔の数値はふくまれていますか

**Comment by manntera** [comment]
@MuhammadJr01 
![image](https://github.com/manntera/arad-buff-score-measure/assets/20245518/67562913-2b86-4744-99fd-1338fac44897)

**Comment by manntera** [comment]
@MuhammadJr01 
スプレッドシートの偏愛ありの計算式の中に、小悪魔の計算が入ってないですね！

**Comment by MuhammadJr01** [comment]
M列がきえてました　修正した

**Comment by manntera** [comment]
よし！計算が一致した！
@MuhammadJr01 
確認ありがとうございます！
@mtakuma1110 
これでマージします～

**Comment by manntera** [comment]
作成したのでクローズ
@mtakuma1110 
偏愛周りのレスポンスに問題あったら教えて下さいー
