### ISSUE TITLE
レスポンス項目のリファクタ

### ISSUE THREAD

**Issue by mtakuma1110** [manntera/arad-buff-score-measure#5]
必須ではないが、APIレスポンスの"ok","error"は"result"にまとめるとよいかも。
また、result項目とerror_message項目の応答パターンは明示されているとありがたいです。
{
    "ok": true,
    "error": "",
    "error_message": "",
    ....
}

**Comment by mtakuma1110** [comment]
#3 へのコメントでよければ取り下げ

**Comment by manntera** [comment]
タスクとして明記しておきたいので残しておきます

**Comment by manntera** [comment]
> 必須ではないが、APIレスポンスの"ok","error"は"result"にまとめるとよいかも。

まとめた

> また、result項目とerror_message項目の応答パターンは明示されているとありがたいです。

もうちょいまって

**Comment by manntera** [comment]
https://github.com/manntera/arad-buff-score-measure/issues/5#issuecomment-2031009230
一旦こっちにIssueたてたのでクローズ
