### ISSUE TITLE
クライアント側の処理時間

### ISSUE THREAD

**Issue by mtakuma1110** [manntera/arad-buff-score-measure#6]
バフアイコンの確認に何秒くらい猶予ある？

**Comment by mtakuma1110** [comment]
> スキルによって持続時間が違う

最短はデスティニーパペットとアドレナリンラプソディーの8秒

しかしバフ順でそういう持続時間が短いスキルを先に打たれると確認猶予時間はさらに短くなる

**Comment by MuhammadJr01** [comment]
勇猛のアリアが一番短かかった
6秒


アリア漏れはこれまでの測定器でもよくあることではあった
