### ISSUE TITLE
ここのリポジトリの通知をWebhook通知させたい

### ISSUE THREAD

**Issue by manntera** [manntera/arad-buff-score-measure#7]
@MuhammadJr01 さんに手順を調べてやってもらうか、
@MuhammadJr01 さんから @manntera に権限を渡してもらって私が設定するか

**Comment by MuhammadJr01** [comment]
アプリで
みれました
メンションがきた

**Comment by MuhammadJr01** [comment]
GitHubの通知をギルドDiscordにWebhookかける
これは私が方法調べてやってみます

**Comment by MuhammadJr01** [comment]
https://support.discord.com/hc/ja/articles/228383668-%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB-Webhooks%E3%81%B8%E3%81%AE%E5%BA%8F%E7%AB%A0

**Comment by MuhammadJr01** [comment]
雪待月の郷DiscordサーバーのwebhookURL

https://discord.com/api/webhooks/1220647753059668009/g1Lyw6oFzRH_5T0NflEcprA5jFZfAIZl6FSriRT6arR-I-d630Jos2-IHUHRykp9AdfS

**Comment by MuhammadJr01** [comment]
@manntera 
GitHubのリポジトリのSetting＞Webhooksメニューを開き雪待月の郷DiscordサーバーのwebhookURLを追加する必要がありますが、リポジトリのSettingを行う権限が私にはないようにおもいます
mannteraさんがリポジトリにWebhook設定するか、私がリポジトリのSettingを開けるようにできませんか

**Comment by manntera** [comment]
@MuhammadJr01 
DIscordでWebHookの権限貰えればこっちでやりますよー。
DIscordのChannelに対して権限を頂ければ

**Comment by manntera** [comment]
DIscordのDMでURLもらった

**Comment by manntera** [comment]
DMログ

⁠雪待月の郷のサーバー⁠
いけましたね
⁠雪待月の郷のサーバー⁠バフスコア測定器開発部門
このチャンネルに通知送る感じにしたいんですけど、いけます？

**Comment by MuhammadJr01** [comment]
通知先の設定を「モハメド戦記」⇒「バススコア測定器開発部門」に変更しました
これでこのまんてらさんのリポジトリの通知はそこにHookされたはず

**Comment by manntera** [comment]
てすてす

**Comment by manntera** [comment]
出来てそうなのでクローズ
